project:
  type: website

website:
  title: "Presentations"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Presentations
        menu:
          - presentations/saf_skyrmions.qmd
          - presentations/sputtering_nucleation.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



